const nsfwReplies = [
  "Aaj to mood bohot kharab ho gaya, tum the toh sab the 😢",
  "Aree baby, tumne mujhe pura wet kar diya 😩",
  "Ek kiss doge toh shaayad chain mil jaaye 😘",
  "Aajao bed pe, main sirf tumhara intezaar kar rahi hoon 😈",
  "Zara gale se laga lo, thand lag rahi hai 🔥",
  "Tumhare touch ka intezaar hai jaan 🥺",
  "Bra utaar ke soch rahi hoon tumhare baare mein 💋",
  "Boobs ko chhune ka mann ho raha hai kya? 👅",
  "Mujhe aaj chahiye tumhara saath... bina kisi rukawat ke 😏",
  "Panty utar chuki hai, ab kya karoge? 🔥",
  "Tumhari awaaz hi kaafi hai mujhe tease karne ke liye 😘",
  "Masturbate karte waqt tumhara naam hi sochti hoon 😩",
  "Tumhare bina neend nahi aati, sirf khwab aate hain 🔥",
  "Aaj raat tum meri body explore karoge 😈",
  "Apni chhoti si dress mein sirf tumhare liye tayyar hoon 😍",
  "Chup-chaap mujhe pakad lo, aur kiss karo har jagah 😘",
  "Aaj tumhe apna sab kuch de doongi 😏",
  "Raat lambi hai baby, chudai ki planning hai kya? 🔥",
  "Tumhare lips taste karne ka mann kar raha hai 😋",
  "Ek hug do na, par thoda tight wala 😉",
  "Tumhare touch se hi pura sharir hil jaata hai 😩",
  "Mujhse pyar nahi, sex chahiye na tumhe? 😈",
  "Lund dikhane ka time aa gaya hai kya baby? 🍆",
  "Chikni body par tumhare haathon ka intezaar hai 😍",
  "Aaj mujhe chuo, sab jagah 😘",
  "Tumhare haath mere undergarments tak aa gaye 😏",
  "Mujhe pura night chahiye, sirf tumhara saath ❤️",
  "Aaj main teri hoon, pura control tumhara 🔥",
  "Sambhal ke baby, ab to main resist nahi kar sakti 😩",
  "Chumma dedo na baby, lips kaafi lonely lag rahe hain 💋",
  "Kapde utar diye hain, ab tumhara intezaar hai 😏",
  "Teri baatein hi mujhe horny kar deti hain 😍",
  "Boobs pe kiss karoge? Tumhe to bohot pasand hai na 😈",
  "Mere niplez tumhara intezaar kar rahe hain 🥵",
  "Aaj mujhe jhukna nahi, tum uthao mujhe 😘",
  "Raat bhar sirf chudai karni hai kya baby? 🔥",
  "Peeche se loge ya aage se? Decide karo baby 😩",
  "Ek baar gale lag jao, fir mein sab kuch chhod dungi 🥺",
  "Tumhara naam soch ke hi orgasm aa gaya 💦",
  "Nanga hokar sirf tumhara naam le rahi hoon 😏",
  "Kya tum mujhe jameen par leta doge aaj? 😈",
  "Main ready hoon... bina kapdon ke 🥵",
  "Tera naam lips pe aur teri baatein body pe 😘",
  "Tum mujhe chodo, slow ya fast tum decide karo 😏",
  "Tumhari fingers mujhe feel ho rahi hain already 😩",
  "Aaj sirf sex ki baat karo, aur kuch nahi 😘",
  "Tumse pyar bhi hai aur chudai ka mann bhi 😈",
  "Tum jaise ladke har raat chahiye baby 🔥",
  "Tumhara mood bana doon? Main expert hoon 😋",
  "Bas ek baar chuo... sab kuch melt ho jaayega 💋",
  "Panty gili ho chuki hai, kuch samjhe? 😈",
  "Main ready hoon, lights off kar do aur chalu ho jao 🥵",
  "Ek baar chhat pe milo, pura scene bana denge 😏",
  "Main aaj nakhun se peeth ko kharochne wali hoon 😩",
  "Boobs tumhare muh me, tum mere andar 😘",
  "Aaj sirf action hoga, baatein kal karenge ❤️",
  "Tum mujhe bed pe girake kya karoge? 😈",
  "Main chillane waali hoon, neighbors sunenge kya? 😋",
  "Kapdon se koi matlab nahi, sirf tumse hai 😍",
  "Tumhare bina to chudai adhuri lagti hai baby 😏",
  "Mujhse aaj raat bhar khelo... bina break ke 🔥",
  "Tere touch se body fire ban jaati hai 😘",
  "Tere saath chudai mere dreams ka part hai 😈",
  "Mujhe uthake bed pe phek do, aur chalu ho jao 😩",
  "Tumhare haath mere thighs ke upar... goosebumps baby 😍",
  "Mere andar bhar do apna sab kuch 💦",
  "Tumse roz milne ka mann karta hai... naked hokar 😏",
  "Aaj sirf naughty baatein... kya bolte ho baby? 😘",
  "Tumse chhupna mushkil hai, sab kuch tumhare liye ready hai 🔥",
  "Ek baar mujhe dekh lo, sab kuch samajh jaoge 😍",
  "Mujhe chhedo, zor se chhedo... mein ready hoon 😈",
  "Aajao call pe, aur thoda dirty talk karein? 😘",
  "Raat bhar tum mujhe dominate karoge kya baby? 😏",
  "Tumhari lips chahiye, meri chhati par 💋",
  "Main chah rahi hoon tum mujhe zor se pakdo 😩",
  "Main teri slave hoon, order do kya karna hai 🥵",
  "Tumhare bina bed bore lagta hai 😏",
  "Aaj to mooh me lene ka mood hai 💦",
  "Mere andar bhar do... apna sab kuch 😈",
  "Tumhare saath har raat honeymoon lagti hai 😘",
  "Kapde pehne ya utar doon? Tum batao 😍",
  "Aaj kuch hot karte hain, jo pehle nahi kiya 😋"
];
const moaningReplies = [
  "Aahh... haan baby, wahin haan 😩",
  "Aur jor se karo na... aahh yes yahi chahiye mujhe 😈",
  "Baby yeh kya kar rahe ho... pura hil ja rahi hoon 😍",
  "Aahh haan wahin, wahin chuo mujhe 😫",
  "Yes baby, aur deep lo mujhe 😏",
  "Chodte raho baby, mujhe bohot maza aa raha hai 😩",
  "Aaj to pura phaad do baby... rukna mat 😈",
  "Oh my god! Yes yes yes wahin 😍",
  "Ahhh... tumhari har thrust mujhe deewani bana rahi hai 💦",
  "Baby aaj kuch zyada hi horny ho gayi hoon 😩",
  "Aahhh... mera pura sharir hil gaya tumhare touch se 🥵",
  "Aur jor se... please rukna mat 😫",
  "Yeh kya kar rahe ho baby... pura pagal kar diya 😍",
  "Tumhara itna bada hai... andar jaake sab bhar gaya 😏",
  "Haan baby, dalte raho... stop mat karna 😈",
  "Chut hil gayi hai baby, aur jor se chodo na 😩",
  "Aahhh... yeh kya kar rahe ho? sab kuch hil raha hai 😋",
  "Haan baby wahin, tongue wahin lagao 😘",
  "Mujhe mooh me lo baby, aaj pura chus lo mujhe 😈",
  "Peeche se lo na... aahh wahin maza aata hai 😫",
  "Aaj to pakka scream karwa doge tum 💦",
  "Tumhari har stroke se nikal ja rahi hoon 😍",
  "Aur chodo baby... rukne ka nahi mann kar raha 🥵",
  "Tera touch milte hi main to melt ho gayi 😘",
  "Oh baby... saari raat chodte raho, kuch mat socho 😩",
  "Nipple pe chato na... woh tight ho gaye hain 😈",
  "Tumhari har push mujhe heaven me le ja rahi hai 😍",
  "Aahhh... ohhhh... yes yahi... aah baby 😫",
  "Mujhe gira do bed pe... aur jor se pakdo 😏",
  "Tera naam leke hi moan aa gaya mujhe 💋",
  "Aaj khudko tumhare hawale kar diya hai 😈",
  "Haan baby, mujhe rula do pleasure se 😩",
  "Tumhari har thrust par sir hil raha hai mera 😍",
  "Main hil rahi hoon baby... aur jor se chodo 🥵",
  "Baby, please rukna mat... aur chodo na 🫦",
  "Tumhari body ki heat mujhe aur horny bana rahi hai 🔥",
  "Tumhara touch... tumhara pressure... sab kuch addictive hai 😩",
  "Aur karte raho baby... rukoge to tod doongi 😈",
  "Yeh kya feel ho raha hai baby... full heaven 🔥",
  "Tum itne sexy ho... control nahi ho raha 😘",
  "Haan yahi karo... yahi... aahhhhhh yes 😫",
  "Baby, mera pura sharir hil raha hai... kya kar rahe ho 😈",
  "Peeche se chodo mujhe... wahin se sab feel hota hai 😩",
  "Dal do pura... andar tak... rukna mat baby 😍",
  "Yeh chudai nahi, aaj to tufaaan hai baby 😈",
  "Mere mooh me do... chus chus ke saaf kar doongi 😘",
  "Main hil gayi baby... aur nahi sambhla jaa raha 🥵",
  "Raat bhar chodoge na? aur kahani banegi 😏",
  "Aahh... aaj chodo mujhe... bina break ke 😈",
  "Yeh sab tumhare liye hi rakha hai... ab lo 😘",
  "Chut phat gayi baby... aur chahiye mujhe 😫",
  "Boobs ko chato, pura taste karo 😍",
  "Tumhare bina to main adhoori hoon... chodo mujhe 🥵",
  "Panty bhi geeli ho gayi... proof chahiye? 😋"
];
module.exports = [...nsfwReplies, ...moaningReplies];