const badWords = {
  // Body parts
  "dick": "lund",
  "cock": "lund",
  "penis": "lund",
  "pussy": "chut",
  "vagina": "chut",
  "boobs": "boobs",
  "breasts": "boobs",
  "ass": "gand",
  "asshole": "gand",
  "butt": "gand",
  "anus": "gand",
  "balls": "andey",
  "testicles": "andey",

  // Common explicit verbs
  "fuck": "chodo",
  "fucking": "chodna",
  "fucked": "choda",
  "screw": "chodo",
  "screwing": "chodna",
  "screwed": "choda",
  "bang": "chodo",
  "banged": "choda",
  "banging": "chodna",
  "suck": "chuso",
  "sucking": "chusna",
  "sucked": "chusa",
  "jerk off": "haath marna",
  "masturbate": "haath marna",
  "cum": "nikal gaya",
  "cumming": "nikalna",
  "ejaculate": "nikalna",
  
  // Phrases
  "fuck me": "mujhe chodo",
  "fuck me harder": "aur zor se chodo",
  "suck my dick": "mera lund chuso",
  "i want to fuck you": "main tumhe chodna chahta hoon",
  "spank me": "mujhe maaro",
  "get fucked": "chud jao",
  "go fuck yourself": "apne aap ko chodo",
  "blow job": "munh mein chusna",
  "hand job": "haath se chusna",
  "oral sex": "munh ka sex",
  "anal sex": "gand ka sex",
  "deep throat": "gehri gardan",
  "strip tease": "kapde utarna",
  "threesome": "teen logon ka sex",
  "porn": "ashleel video",
  "pornstar": "ashleel star",
  "sex": "sex",
  "sexual": "yaoni sambandh",
  "horny": "hawa chali hai",
  "wet pussy": "gili chut",
  "tight pussy": "sakht chut",
  "big boobs": "bade chuchiyaan",
  "small boobs": "chhoti chuchiyaan",

  // Insults & Slang
  "bitch": "kutti",
  "slut": "randi",
  "whore": "randi",
  "hoe": "randi",
  "cunt": "chut",
  "dumbass": "bewakoof",
  "asshole": "gand",
  "son of a bitch": "kutti ka beta",
  "motherfucker": "maa chodne wala",
  "bastard": "harami",
  "jerk": "gand",
  "dickhead": "lund ka sira",
  "pussy": "chut",
  "twat": "chut",
  
  // Misc
  "nude": "nanga",
  "naked": "nanga",
  "sexy": "sexy",
  "hot": "garam",
  "fuck off": "bhag yahan se",
  "get lost": "nikal yahan se",
  "cum inside": "andar nikalo",
  "spread legs": "taang kholo",
  "ride me": "mujhe sawar ho",
  "lick my pussy": "mera chut chaat",
  "kiss my ass": "meri gand chum",
  "make love": "pyaar karo",
  "blow me": "mujhe chus",
  "hard cock": "sakht lund",
  "soft cock": "naram lund",

  // Add more sexual acts & slang
  "69": "sath-sath chusna",
  "orgasm": "orgasm",
  "cumshot": "nikalna",
  "rimming": "gand chaatna",
  "fisting": "muthi maarna",
  "dirty talk": "gandi baatein",
  "fetish": "dilchaspi",
  "bondage": "bandhan",
  "dominant": "hakim",
  "submissive": "mazdoor",
  "lesbian": "ladkiyon ka pyaar",
  "gay": "gay",
  "bi": "do taraf wala",
  "transgender": "transgender",
  
  // Expletives
  "shit": "gand",
  "damn": "sala",
  "hell": "narak",
  "crap": "bekaar",
  "piss": "peshab",
  "bastard": "harami",
  "bloody": "khooni",
  "bugger": "chutiya",
  "bollocks": "bakwas",
  "arse": "gand",
  "twat": "chut",
  "wanker": "haath marne wala",
  "tosser": "bewakoof",
  "knob": "lund",
  "prick": "lund",
  "shithead": "gand ka sira",
  "muff": "chut",
  "douche": "gand mara banda",

  // More phrases / intensifiers
  "fuck off": "bhag yahan se",
  "fuck you": "tujhe chodo",
  "fuck that": "usko chodo",
  "fuck this": "isko chodo",
  "eat my ass": "meri gand chuo",
  "bite my ass": "meri gand kaat",
  "piss off": "nikal yahan se",
  "shut up": "chup ho jao",
  "get out": "nikal yahan se",
  "go away": "door jao",
  "i want you": "mujhe tum chahiye",
  "i love you": "main tumse pyaar karta hoon",

  // Random common NSFW words
  "clitoris": "clitoris",
  "labia": "labia",
  "erection": "khatta hua lund",
  "wet": "gila",
  "naughty": "shaitaan",
  "seduce": "bhaavna karna",
  "tease": "chhedna",
  "playboy": "masti karne wala",
  "cumshot": "nikal gaya",
  "stripper": "kapde utarne wali",

  // More crude terms
  "fellatio": "munh mein chusna",
  "cunnilingus": "chut chaatna",
  "anal": "gand",
  "smegma": "gand ka mail",
  "glans": "lund ka sir",
  "shaft": "lund ki danda",
};
function isNSFW(text) {
  return badWords.some(word => text.toLowerCase().includes(word));
}

module.exports = isNSFW;